### ISSUE TITLE
Transferir chamadas da antiga View para os Controllers

### ISSUE THREAD

**Issue by fdpeiter** [jeanschuchardt/Tele-HealthCare#10]

**Comment by fdpeiter** [comment]
Material de apoio: http://www.cs.wcupa.edu/rkline/java/mvc-design.html

**Comment by jeanschuchardt** [comment]
http://stackoverflow.com/questions/5217611/the-mvc-pattern-and-swing

**Comment by fdpeiter** [comment]
https://www.link-intersystems.com/blog/2013/07/20/the-mvc-pattern-implemented-with-java-swing/
